### ISSUE TITLE
Unit tests that cross threads

### ISSUE THREAD

**Issue by MCFHTAGENTS** [lucaslorentz/minicover#119]
Lucas,
hi there - Based on what i am observing with my testing and use of your tool I don't think you are correctly capturing activity when it is performed in a worker thread.

I guess we can have a  debate about should a unit test cross a thread boundary but as part of what I am emulating is a socket it would be helpful if it did this.
Thanks
Mark

**Comment by lucaslorentz** [comment]
Is this issue still happening?
Can you please provide a repository with a reproducible scenario?

**Comment by MCFHTAGENTS** [comment]
Lucas
I haven't used this for a while but I haven't seen a new version so I assume it is. Basically the functions in a worker thread were not being logged. If you have an app with a worker thread lying around can you try instrumenting that. Otherwise I can try and create one but am probably going to be banned from the PC over Christmas :)
Thanks
Mark

**Comment by lucaslorentz** [comment]
Hey Mark,

No problem. I did those tests https://github.com/lucaslorentz/minicover/pull/135/commits/56eb2e8dcc93645ce93a2b8870ec920527c46747 and they're passing. 

It was probably fixed by release https://github.com/lucaslorentz/minicover/releases/tag/v3.2.0

I will close this issue, please re-open if you face that problem again.

Enjoy Christmas!
