### ISSUE TITLE
Cannot install minicover

### ISSUE THREAD

**Issue by eklnc** [lucaslorentz/minicover#123]
Documentation cannot working to me. I have net core 3.1 console app. Following install code cannot working.

dotnet tool install --global minicover

Error is below:
 error : Failed to retrieve information about 'minicover' from remote source 'http://nuget.solvoyo.com/nuget/FindPackagesById()?id='minicover'&semVerLevel=2.0.0'.

And

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

---

Tool 'minicover' failed to install.

**Comment by lucaslorentz** [comment]
There is some nuget.config configured in your machine with nuget source nuget.solvoyo.com.
For some reason that source was not available at the moment you tried to install minicover, affecting the whole installation.

Try re-configuring your nuget.config, making sure nuget.org source is still there and all the sources configured are available.

You can also try the command below, but it might not work because nuget.solvoyo.com will be used before nuget.org. 
```
dotnet tool install --global minicover --add-source https://api.nuget.org/v3/index.json
```

**Comment by eklnc** [comment]
Thank you!
