### ISSUE TITLE
Not all reports support threshold and noFail

### ISSUE THREAD

**Issue by VladislavAntonyuk** [lucaslorentz/minicover#125]
Some reports like coberturareport, cloverreport, coverallsreport, opencoverreport, xmlreport do not support threshold and noFail options

**Comment by lucaslorentz** [comment]
We had a threshold option on those reports some versions ago, but it was removed recently because it was only used to fail the command if the threshold is not met.

The idea now is to only support the threshold option when it affects the report output.
If you need to check the threshold, you need to execute a report or HTML report along with the reports above. Or in the future, we might include a new report command just to check the threshold and coverage totals.

AFAIK all file formats above don't support storing a threshold.

Maybe you can double-check the specification of each one of those formats, and let me known which ones could make use of threshold information.
