### ISSUE TITLE
coveralls.io support

### ISSUE THREAD

**Issue by aseduto** [lucaslorentz/minicover#63]
Hi,

Are you planning in implementing coveralls.io support?

It would be useful when using remote build servers in reviewing coverage results.

Thank you.

aseduto

**Comment by lucaslorentz** [comment]
I guess it is already possible to integrate with coveralls because we can generate open-cover xml reports.

Check those samples, and replace the opencover commands part by minicover.
https://github.com/csmacnz/Coveralls.net-Samples

I will also try something when I have some time, I do want to have a badge on this repository.

**Comment by aseduto** [comment]
Hi Lucas,
Looking to the csmacnz the tool does not seem to be integrated with dotnet core but with the full framework.
This could be a challenge.
I will try to integrate with coverall and let you know.

**Comment by lucaslorentz** [comment]
Coveralls was integrated.
Thanks @aseduto 

There is still a coverage issue about considering lambda functions as covered because declaration/assigned instruction covers all lines. But that's not related to coveralls, I still need to fix it.
