### ISSUE TITLE
parameters as a file

### ISSUE THREAD

**Issue by day01** [lucaslorentz/minicover#68]
What do you think about yaml/json configuration instead cmd line parameters?
All option will be in the file: source, excludes, workdir, etc

**Comment by lucaslorentz** [comment]
I think yaml or json configuration should be outside the scope of this project for now.

Now coverage exclusions can also be configured using [ExcludeFromCodeCoverage] attribute.
And now we have good defaults for sources, assemblies inclusions/exclusions.

I hope that mitigates a bit your need for yaml/json configuration.

**Comment by duaneking** [comment]
@lucaslorentz We really need optional external config files for exclusions.  Modifying code for this by adding attributes also violates SOLID and actively creates more problems ; May I ask why you are so against such a massively requested for feature?  

Attributes do not work for most of our tests cases, and honestly just clutter up code.  And it is not just a code cleanliness issue, its also the fact that now code and build systems have to change to add exclusions when with a config file it would be a one file change instead of a thousands of files change because a configuration file is the inflection point.

**Comment by lucaslorentz** [comment]
@duaneking you shouldn't add attribute to ignore code coverage on all your tests. That sounds terrible.

By default minicover only measure coverage of files inside src folder. That usually doesn't include test files as Microsoft best practices recommends putting them in a test folder.

If you don't follow that folder structure. Just customize options --sources and --exclude-sources to only match your source files and not match test files. There is some info in readme page.

Something like --exclude-sources **/*Test*/**/*.cs might do the trick if you put your tests inside a folder that has Test in its name.

**Comment by duaneking** [comment]
What about the fact that in most projects I have seen in the wild, both tests and product code live under ./src/  as separate projects as part of the same solution? For example, ./src/product/* and ./src/product.tests/* is the pattern I see used the most because it is clean, allows a separation of concerns, but also allow dev's to run any tests they need to locally.  In most cases, there can be 100's of smaller projects living under that root as separations of concern are partitioned out and made explicit in each small project library, each with its own custom tests and the project/directory structure to match.  That's what is driving this request.

I'm obviously not a fan of using attributes at all for coverage as I consider it a huge violation of SOLID; But right now we are forced to manage our CI/CD bitbucket-pipelines.yaml file manually and its a PITA to manage.
