### ISSUE TITLE
Tests that throws exceptions doesn't record any hits

### ISSUE THREAD

**Issue by lucaslorentz** [lucaslorentz/minicover#83]
If a test method throws an exception, the hit lines before the exception was thrown are not recorded on the hits file.
That's because we only write the hits when the method execution finishes, and we don't handle exceptions on our instrumentation.

**Comment by bhugot** [comment]
The point is that instrumenting the Exit method Is one of the most harder part causing many problems (even without try finally it's not working correctly in F# by example).
As I told you I think we should find all tests methods and then instrument them with the try-finally as they are simpliest one.
I doesn't mean we need to do a full instrumentation on them.

The fact that we use a communication service to save the hits instead of saving when calling exit could be a good thing but it will not fix the issue with the exit method.

**Comment by lucaslorentz** [comment]
Can you take a look on this Finally implementation?
https://github.com/Fody/MethodTimer/blob/master/MethodTimer.Fody/MethodProcessor.cs

It seems simpler than what we had.

**Comment by lucaslorentz** [comment]
If we go that path again, we need to collect sample projects that was failing, so we can test it extensively.

**Comment by bhugot** [comment]
@lucaslorentz maybe some part are simpler last version we had was not that bad. But wasn't working with F#. The difference with method processor is that we need to handle before ctor but I think that part is working well. So I should give a try on my branch with this implementation.

**Comment by MurilloBatalha** [comment]
Is there any plans to fix this issue? 

I liked minicover a lot, since it can group coverage across multiple tests projects (I have a unit test project and one for integration tests) and work with dotnet cli.

**Comment by lucaslorentz** [comment]
@MurilloBatalha 
I didn't have much time to work on this project lately.
If you find any alternative that suits you well, I recommend to go for it.

I would like to work at least on the major issues in the future, but I don't know when I will do it.

**Comment by ghandmann** [comment]
+1 for fixing this. This is currently a big bummer for us since we try to optimize our UnitTests based on the CoverageReport, which has holes everywhere because of this.

**Comment by lucaslorentz** [comment]
Fixed on version [v3.0.0-alpha-1](https://github.com/lucaslorentz/minicover/releases/tag/v3.0.0-alpha-1)
